name: "consistency-refine-long"
tag: "${rmspace:${system.prompt_processor.prompt},_}"
exp_root_dir: "outputs"
seed: 43

data_type: "random-camera-datamodule"
data:
  batch_size: 12
  width: 512
  height: 512
  camera_distance_range: [1.5, 2.0]
  elevation_range: [-10, 45]
  light_sample_strategy: "magic3d"
  fovy_range: [30, 45]
  eval_camera_distance: 2.0
  eval_fovy_deg: 45.
  camera_perturb: 0.
  center_perturb: 0.
  up_perturb: 0.

  batch_uniform_azimuth: true
  n_val_views: 4
  use_n_views: True
  n_views: 4
  azimuth_range: [-135, 225]

system_type: "consistency-system"
system:
  refinement: true
  texture: false
  geometry_only: true
  # If using geometry from previous training
  geometry_convert_from: ???
  geometry_type: "tetrahedra-sdf-grid"
  geometry_convert_override:
    isosurface_threshold: 10.
  geometry:
    radius: 2.0
    isosurface_resolution: 128
    isosurface_deformable_grid: true
    pos_encoding_config:
      otype: HashGrid
      n_levels: 16
      n_features_per_level: 2
      log2_hashmap_size: 19
      base_resolution: 16
      per_level_scale: 1.4472692374403782 # max resolution 4096
    n_feature_dims: 0
    fix_geometry: false
    geometry_only: true
  
  material_type: "no-material" # unused
  material:
    n_output_dims: 0

  background_type: "solid-color-background" # unused

  renderer_type: "nvdiff-rasterizer"
  renderer:
    context_type: cuda

  prompt_processor_type: "stable-diffusion-prompt-processor"
  prompt_processor:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    prompt: ???

  guidance_type: "stable-diffusion-guidance"
  guidance:
    pretrained_model_name_or_path: "stabilityai/stable-diffusion-2-1-base"
    weighting_strategy: sds
    guidance_scale: [0, 100., 20., 5000]
    recon_std_rescale: 0.0
    min_sigma_percent: 0.02
    max_sigma_percent: 0.5
    min_step_percent: 0.02
    max_step_percent: 0.5
    loss_type: consistency_ori
    cur_steps: [0, 300, 20, 5000]
    grad_clip: [0, 2.0, 8.0, 5000]
    share_noise: true
    perturb_indices: sqrt
    perturb_factor: 100
    end_gap: 100
  freq:
    guidance_eval: 1000

  loggers:
    wandb:
      enable: false
      project: "threestudio"

  loss:
    lambda_sds: 1.
    lambda_normal_consistency: 100.
    lambda_laplacian_smoothness: 100.

  optimizer:
    name: Adan
    args:
      eps: 1.0e-8
      lr: 0.005
      weight_decay: 2.0e-8
      max_grad_norm: 5.0
      foreach: True
      fused: False

trainer:
  max_steps: 5000
  log_every_n_steps: 1
  num_sanity_val_steps: 1
  val_check_interval: 1000
  enable_progress_bar: true
  precision: 16-mixed

checkpoint:
  save_last: true # save at each validation time
  save_top_k: -1
  every_n_train_steps: ${trainer.max_steps}
